do both directions

diff --git a/t/hash-count b/t/hash-count
--- a/t/hash-count
+++ b/t/hash-count
@@ -10,12 +10,16 @@ cd "$(dirname "$0")"
 out=$(mktemp -t hash-count-swe-dan.XXXXXXXXXX)
 trap 'rm -f "${out}"' EXIT
 
-cat ../texts/*.swe.txt | apertium -f html-noent -d .. swe-dan > "${out}"
+for dir in swe-dan dan-swe; do
+    src=${dir%%-*}
 
-current=$(grep -c '[#@]' "${out}" || true)
+    cat ../texts/*."${src}".txt | apertium -f html-noent -d .. "${dir}" > "${out}"
 
-if [[ "${current}" -gt 0 ]]; then
-    echo "ERROR: texts/*.swe.txt translated through swe-dan gave debug sybols [#@]:"
-    grep -n '[#@]' "${out}"
-    exit 1
-fi
+    current=$(grep -c '[#@]' "${out}" || true)
+
+    if [[ "${current}" -gt 0 ]]; then
+        echo "ERROR: texts/*.${src}.txt translated through ${dir} gave debug sybols [#@]:"
+        grep -n '[#@]' "${out}"
+        exit 1
+    fi
+done
